In [ ]:
import cv2
import numpy as np

#load image in grayscale
face_img = cv2.imread("face.png", cv2.IMREAD_GRAYSCALE)

#convert to NumPy array
face_matrix = np.array(face_img)

print(face_matrix[:3, :3])


[[182 182 181]
 [182 182 181]
 [182 182 181]]


In [5]:
import numpy
myMatrix = numpy.array([[1,2,3], [4,5,6], [7,8,9]])
print(myMatrix[1:2, 2:3])

[[6]]
