In [1]:
%pip install deepface

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
%pip install tf-keras

   ---------------------------------------- 0.0/1.7 MB ? eta -:--:--
   ---------------------------------------- 1.7/1.7 MB 15.2 MB/s eta 0:00:00
Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 24.2 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [8]:
import cv2
import numpy 

face = cv2.imread('./group.jpg', cv2.IMREAD_GRAYSCALE)

matrix = numpy.array(face)
print(matrix[:5,:5])
print(matrix.shape)
print(matrix)

#print(matrix[355:360, 584:589])

[[17 17 17 18 18]
 [18 18 18 18 18]
 [19 19 19 19 18]
 [21 21 21 20 19]
 [22 22 22 21 20]]
(360, 589)
[[ 17  17  17 ...  61  64  67]
 [ 18  18  18 ...  60  63  66]
 [ 19  19  19 ...  58  62  64]
 ...
 [117 123 121 ... 221 221 221]
 [118 127 125 ... 222 221 221]
 [123 133 128 ... 222 222 221]]
